[tool.poetry]
name = "poetry-docker"
version = "0.1.0"
description = ""
authors = ["qq <qq@i.ua>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = "^4.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
